"""Write a recomp input script that teleports through Challenge Map > Locations and listens at each.

usage: py -3.13 make_location_script.py <out.txt> <district index> <listen seconds> <name>...
  district index: 0 Downtown, 1 Industrial, 2 University (order of the Locations list).
  Each name is one location in list order (index = position in the district's list, 0-based), given as
  `<index>:<Name>`, e.g. `0:Aletown 2:Carverton_Memorial_Park`.
Menu path (2026-10-02): start, a (Challenge Map), rt, rt (Locations), down x district, a, down x location,
a, a, a; then `gameplay` waits for steady gameplay after the load.
"""
import sys
from pathlib import Path


def main() -> None:
    out, district, listen = Path(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
    lines = [f'# Locations of district {district}, {listen} s each (generated by make_location_script.py).', '1500 # settle']
    for spec in sys.argv[4:]:
        index, name = spec.split(':', 1)
        lines += [' 165 start', '1246', ' 133 a', '1049', ' 133 rt', ' 513', ' 148 rt', '1800']
        lines += [' 150 down', ' 450'] * district
        lines += [' 133 a', '1200']
        lines += [' 150 down', ' 450'] * int(index)
        lines += [' 133 a', ' 700', ' 133 a', ' 700', ' 133 a', f'4000 gameplay # at {name}', f'{listen * 1000} # listen {name}']
    lines.append('100 # done')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{out}: {len(sys.argv) - 4} locations')


if __name__ == '__main__':
    main()
